/**
 * Comprehensive India Government Exam Discovery Platform Dataset
 * Over 50+ Real Government Exams across 11 Major Sectors
 */

function getDiscoveryExams() {
  return [
    // ==========================================
    // 1. UPSC (Civil Services & Central Services)
    // ==========================================
    {
      id: 'exam_upsc_cse',
      code: 'UPSC CSE',
      name: 'UPSC Civil Services Examination (IAS/IPS/IFS/IRS)',
      organization: 'Union Public Service Commission',
      category: 'UPSC',
      sub_category: 'All India & Central Services',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline from a recognized University',
      age_min: 21,
      age_max: 32,
      salary_min: 56100,
      salary_max: 250000,
      pay_level: 'Level 10 to Level 17 (Apex Scale)',
      in_hand_salary: '₹75,000 - ₹1,20,000 / month (Entry Level)',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'All India',
      description: 'The premier national civil service examination for recruitment to Indian Administrative Service (IAS), Indian Police Service (IPS), Indian Foreign Service (IFS), and Central Group A & B Services.',
      selection_process: JSON.stringify(['Stage 1: Preliminary Exam (GS-I & CSAT - Objective)', 'Stage 2: Main Examination (9 Descriptive Papers)', 'Stage 3: Personality Test / Interview']),
      exam_pattern_summary: 'Prelims: 400 Marks (2 Papers of 200 Marks each). Mains: 1750 Marks (7 Merit Papers). Interview: 275 Marks. Negative Marking: 1/3rd in Prelims.',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 2025,
      duration_minutes: 120,
      dates: {
        cycle_name: 'UPSC CSE 2026 Cycle',
        year: 2026,
        notification_date: '2026-02-11',
        application_start: '2026-02-11',
        application_end: '2026-03-03',
        admit_card_date: '2026-05-10',
        exam_date: '2026-05-24',
        result_date: '2026-06-25',
        interview_date: '2026-12-15',
        final_result_date: '2027-04-15',
        status: 'Exam Ongoing'
      }
    },
    {
      id: 'exam_upsc_ese',
      code: 'UPSC ESE',
      name: 'Engineering Services Examination (IES / ESE)',
      organization: 'Union Public Service Commission',
      category: 'UPSC',
      sub_category: 'Central Technical Engineering Services',
      qualification: 'B.E/B.Tech',
      degree_required: 'Degree in Civil, Mechanical, Electrical, or Electronics & Telecommunication Engineering',
      age_min: 21,
      age_max: 30,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10 (₹56,100 - ₹1,77,500)',
      in_hand_salary: '₹75,000 - ₹95,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Technical',
      state: 'All India',
      description: 'Recruitment for Group A engineering posts across Indian Railways, Central Engineering Services (CPWD), Military Engineer Services (MES), and Indian Ordnance Factories.',
      selection_process: JSON.stringify(['Stage 1: Preliminary Stage (Paper-I GS & Engg Aptitude + Paper-II Discipline)', 'Stage 2: Mains Conventional Stage (2 Technical Papers)', 'Stage 3: Personality Test (Interview)']),
      exam_pattern_summary: 'Prelims: 500 Marks (Objective). Mains: 600 Marks (Conventional). Personality Test: 200 Marks.',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 1300,
      duration_minutes: 180,
      dates: {
        cycle_name: 'ESE 2027 Cycle',
        year: 2027,
        notification_date: '2026-09-16',
        application_start: '2026-09-16',
        application_end: '2026-10-06',
        admit_card_date: '2027-01-25',
        exam_date: '2027-02-14',
        result_date: '2027-03-30',
        interview_date: '2027-08-10',
        final_result_date: '2027-11-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_upsc_capf',
      code: 'UPSC CAPF',
      name: 'Central Armed Police Forces (Assistant Commandants)',
      organization: 'Union Public Service Commission',
      category: 'UPSC',
      sub_category: 'Paramilitary Officer Cadre',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any stream',
      age_min: 20,
      age_max: 25,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10 (Assistant Commandant)',
      in_hand_salary: '₹75,000 - ₹90,000 / month + Risk Allowances',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Uniformed / Defence',
      state: 'All India',
      description: 'Officer rank recruitment for BSF, CRPF, CISF, ITBP, and SSB under Ministry of Home Affairs.',
      selection_process: JSON.stringify(['Stage 1: Written Examination (Paper-I General Ability & Intelligence, Paper-II Essay & Comprehension)', 'Stage 2: Physical Standards & Efficiency Test (PST/PET) & Medical Exam', 'Stage 3: Interview / Personality Test']),
      exam_pattern_summary: 'Paper-I: 250 Marks (Objective), Paper-II: 200 Marks (Descriptive), Interview: 150 Marks.',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-18',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 600,
      duration_minutes: 120,
      dates: {
        cycle_name: 'CAPF (AC) 2026 Cycle',
        year: 2026,
        notification_date: '2026-04-22',
        application_start: '2026-04-22',
        application_end: '2026-05-12',
        admit_card_date: '2026-07-20',
        exam_date: '2026-08-02',
        result_date: '2026-09-30',
        interview_date: '2026-11-15',
        final_result_date: '2027-01-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_upsc_ies_iss',
      code: 'UPSC IES/ISS',
      name: 'Indian Economic Service & Indian Statistical Service',
      organization: 'Union Public Service Commission',
      category: 'UPSC',
      sub_category: 'Specialized Cadre',
      qualification: 'Postgraduate',
      degree_required: 'Master Degree in Economics / Applied Economics / Statistics',
      age_min: 21,
      age_max: 30,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10',
      in_hand_salary: '₹75,000 - ₹95,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'All India',
      description: 'Specialized cadre serving in Ministry of Finance, NITI Aayog, CSO, NSSO, and key economic ministries.',
      selection_process: JSON.stringify(['Stage 1: Written Examination (6 Papers - 1000 Marks)', 'Stage 2: Viva-Voce / Interview (200 Marks)']),
      exam_pattern_summary: 'General English & General Studies (200 Marks) + 4 Subject Papers (800 Marks) + Viva (200 Marks).',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-15',
      status: 'Upcoming',
      is_popular: 0,
      is_featured: 0,
      total_marks: 1200,
      duration_minutes: 180,
      dates: {
        cycle_name: 'IES/ISS 2026',
        year: 2026,
        notification_date: '2026-04-08',
        application_start: '2026-04-08',
        application_end: '2026-04-28',
        admit_card_date: '2026-06-05',
        exam_date: '2026-06-19',
        result_date: '2026-08-15',
        interview_date: '2026-10-20',
        final_result_date: '2026-12-10',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 2. SSC (Staff Selection Commission)
    // ==========================================
    {
      id: 'exam_ssc_cgl',
      code: 'SSC CGL',
      name: 'SSC Combined Graduate Level Examination (CGL)',
      organization: 'Staff Selection Commission',
      category: 'SSC',
      sub_category: 'Central Ministries Group B & C',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline from a recognized University',
      age_min: 18,
      age_max: 32,
      salary_min: 35400,
      salary_max: 142400,
      pay_level: 'Level 4 to Level 8 (Inspector, ASO, Tax Assistant)',
      in_hand_salary: '₹45,000 - ₹82,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'National recruitment for Assistant Section Officer (CSS, MEA, IB, Railway), Income Tax Inspector, GST Inspector, Sub-Inspector in CBI, and Auditor.',
      selection_process: JSON.stringify(['Tier-I: Computer Based Examination (Objective Qualifying)', 'Tier-II: Computer Based Examination (Paper-I Math, Reasoning, English, GA, Computer, Typing)', 'Document Verification & Medical']),
      exam_pattern_summary: 'Tier-1: 100 Questions (200 Marks, 60 Mins, Negative 0.50). Tier-2: Paper-1 (390 Marks + Qualifying Computer & Typing Test).',
      official_url: 'https://ssc.gov.in',
      last_verified: '2026-08-26',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 390,
      duration_minutes: 135,
      dates: {
        cycle_name: 'SSC CGL 2026 Cycle',
        year: 2026,
        notification_date: '2026-06-11',
        application_start: '2026-06-11',
        application_end: '2026-07-10',
        admit_card_date: '2026-09-01',
        exam_date: '2026-09-15',
        result_date: '2026-11-20',
        interview_date: null,
        final_result_date: '2027-02-15',
        status: 'Application Open'
      }
    },
    {
      id: 'exam_ssc_chsl',
      code: 'SSC CHSL',
      name: 'SSC Combined Higher Secondary Level (10+2 CHSL)',
      organization: 'Staff Selection Commission',
      category: 'SSC',
      sub_category: 'Central Ministries 12th Pass',
      qualification: '12th',
      degree_required: '12th Standard or equivalent from a recognized board',
      age_min: 18,
      age_max: 27,
      salary_min: 25500,
      salary_max: 81100,
      pay_level: 'Level 2 & Level 4 (LDC, JSA, DEO)',
      in_hand_salary: '₹32,000 - ₹45,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'Recruitment of Lower Division Clerks (LDC), Junior Secretariat Assistants (JSA), and Data Entry Operators (DEO) across Central Government Ministries.',
      selection_process: JSON.stringify(['Tier-I: Computer Based Examination (Objective)', 'Tier-II: Objective Test + Skill Test / Typing Test']),
      exam_pattern_summary: 'Tier-1: 100 Qs / 200 Marks. Tier-2: Math, Reasoning, English, GA, Computer Knowledge & Typing Speed 35 wpm.',
      official_url: 'https://ssc.gov.in',
      last_verified: '2026-08-22',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 360,
      duration_minutes: 60,
      dates: {
        cycle_name: 'SSC CHSL 2026',
        year: 2026,
        notification_date: '2026-04-02',
        application_start: '2026-04-02',
        application_end: '2026-05-01',
        admit_card_date: '2026-06-20',
        exam_date: '2026-07-05',
        result_date: '2026-08-30',
        interview_date: null,
        final_result_date: '2026-11-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_ssc_mts',
      code: 'SSC MTS',
      name: 'SSC Multi-Tasking (Non-Technical) Staff & Havaldar',
      organization: 'Staff Selection Commission',
      category: 'SSC',
      sub_category: 'Central 10th Pass Recruitment',
      qualification: '10th',
      degree_required: 'Matriculation (10th Pass) from recognized Board',
      age_min: 18,
      age_max: 27,
      salary_min: 18000,
      salary_max: 56900,
      pay_level: 'Level 1 (7th CPC)',
      in_hand_salary: '₹26,000 - ₹34,000 / month',
      difficulty: 'beginner',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'General support and administrative operational assistance in various Central Government Ministries, Departments, and CBIC/CBN Havaldar posts.',
      selection_process: JSON.stringify(['Session-I: Numerical & Mathematical Ability, Reasoning Ability (No Negative Marking)', 'Session-II: General Awareness, English Language (Negative 1 mark)', 'Physical Efficiency Test (PET/PST for Havaldar only)']),
      exam_pattern_summary: 'Computer Based Examination in 13 Regional Languages + English and Hindi.',
      official_url: 'https://ssc.gov.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 270,
      duration_minutes: 90,
      dates: {
        cycle_name: 'SSC MTS 2026',
        year: 2026,
        notification_date: '2026-05-07',
        application_start: '2026-05-07',
        application_end: '2026-06-06',
        admit_card_date: '2026-09-10',
        exam_date: '2026-09-28',
        result_date: '2026-11-15',
        interview_date: null,
        final_result_date: '2027-01-10',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_ssc_cpo',
      code: 'SSC CPO',
      name: 'SSC Sub-Inspector in Delhi Police & CAPFs',
      organization: 'Staff Selection Commission',
      category: 'SSC',
      sub_category: 'Central Police Sub-Inspector',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any stream + Driving License (for Delhi Police)',
      age_min: 20,
      age_max: 25,
      salary_min: 35400,
      salary_max: 112400,
      pay_level: 'Level 6 (Sub-Inspector)',
      in_hand_salary: '₹50,000 - ₹62,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Police',
      state: 'All India',
      description: 'Sub-Inspector recruitment in Delhi Police, BSF, CISF, CRPF, ITBP, and SSB.',
      selection_process: JSON.stringify(['Paper-I: General Intelligence, GK, Quant, English (200 Marks)', 'Physical Standard Test (PST) & Physical Endurance Test (PET)', 'Paper-II: English Language & Comprehension (200 Marks)', 'Detailed Medical Examination (DME)']),
      exam_pattern_summary: 'Paper-I (200 Marks) + Paper-II (200 Marks). Merit list based on aggregate score + NCC certificate bonus.',
      official_url: 'https://ssc.gov.in',
      last_verified: '2026-08-19',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 400,
      duration_minutes: 120,
      dates: {
        cycle_name: 'SSC CPO 2026',
        year: 2026,
        notification_date: '2026-02-15',
        application_start: '2026-02-15',
        application_end: '2026-03-14',
        admit_card_date: '2026-05-01',
        exam_date: '2026-05-15',
        result_date: '2026-07-20',
        interview_date: null,
        final_result_date: '2026-12-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_ssc_je',
      code: 'SSC JE',
      name: 'SSC Junior Engineer (Civil, Mechanical, Electrical)',
      organization: 'Staff Selection Commission',
      category: 'SSC',
      sub_category: 'Central Technical Engineering Diploma/Degree',
      qualification: 'Diploma',
      degree_required: 'Diploma or Degree in Civil / Electrical / Mechanical Engineering',
      age_min: 18,
      age_max: 30,
      salary_min: 35400,
      salary_max: 112400,
      pay_level: 'Level 6 (Junior Engineer)',
      in_hand_salary: '₹48,000 - ₹58,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Technical',
      state: 'All India',
      description: 'Junior Engineers in CPWD, MES, Central Water Commission (CWC), Farakka Barrage, and Border Roads Organization (BRO).',
      selection_process: JSON.stringify(['Paper-I: Computer Based Exam (General Intelligence, General Awareness, Engineering Technical - 200 Marks)', 'Paper-II: Computer Based Technical Domain Exam (300 Marks)']),
      exam_pattern_summary: 'Paper-I: 200 Marks (2 Hours). Paper-II: 300 Marks (2 Hours). Negative marking 0.25 (Paper-I) and 1.0 (Paper-II).',
      official_url: 'https://ssc.gov.in',
      last_verified: '2026-08-21',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 500,
      duration_minutes: 120,
      dates: {
        cycle_name: 'SSC JE 2026',
        year: 2026,
        notification_date: '2026-03-28',
        application_start: '2026-03-28',
        application_end: '2026-04-18',
        admit_card_date: '2026-05-25',
        exam_date: '2026-06-10',
        result_date: '2026-08-10',
        interview_date: null,
        final_result_date: '2026-11-20',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 3. RAILWAYS (RRB)
    // ==========================================
    {
      id: 'exam_rrb_ntpc',
      code: 'RRB NTPC',
      name: 'Railway RRB Non-Technical Popular Categories (NTPC)',
      organization: 'Railway Recruitment Control Board',
      category: 'Railways',
      sub_category: 'Station Master, Goods Guard, Clerks',
      qualification: 'Any Degree',
      degree_required: '12th Pass (for Undergraduate Level) or Any Degree (for Graduate Level)',
      age_min: 18,
      age_max: 33,
      salary_min: 21700,
      salary_max: 112400,
      pay_level: 'Level 2 to Level 6 (7th CPC)',
      in_hand_salary: '₹35,000 - ₹65,000 / month + Running Allowances',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'Major railway recruitment for Station Master, Train Manager (Goods Guard), Senior Commercial cum Ticket Clerk, Accounts Clerk, and Junior Clerk.',
      selection_process: JSON.stringify(['Stage 1: 1st Stage Computer Based Test (CBT-1 Screening)', 'Stage 2: 2nd Stage Computer Based Test (CBT-2 Level-wise)', 'Stage 3: Computer Based Aptitude Test (CBAT) / Typing Skill Test', 'Stage 4: Document Verification & Medical Examination']),
      exam_pattern_summary: 'CBT-1: 100 Qs (GA 40, Math 30, Reasoning 30) - 90 mins. CBT-2: 120 Qs (GA 50, Math 35, Reasoning 35) - 90 mins. Negative: 1/3rd.',
      official_url: 'https://rrbcdg.gov.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 120,
      duration_minutes: 90,
      dates: {
        cycle_name: 'RRB NTPC 2026 Cycle',
        year: 2026,
        notification_date: '2026-09-05',
        application_start: '2026-09-05',
        application_end: '2026-10-04',
        admit_card_date: '2026-12-10',
        exam_date: '2026-12-20',
        result_date: '2027-02-15',
        interview_date: null,
        final_result_date: '2027-06-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_rrb_alp',
      code: 'RRB ALP',
      name: 'RRB Assistant Loco Pilot (ALP)',
      organization: 'Railway Recruitment Control Board',
      category: 'Railways',
      sub_category: 'Loco Operations',
      qualification: 'Diploma',
      degree_required: 'Matriculation + ITI / Diploma in Mechanical / Electrical / Electronics / Auto Engg or B.E/B.Tech',
      age_min: 18,
      age_max: 30,
      salary_min: 19900,
      salary_max: 63200,
      pay_level: 'Level 2 + Running Allowance (Km rate)',
      in_hand_salary: '₹40,000 - ₹55,000 / month',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Technical',
      state: 'All India',
      description: 'Piloting train locomotives and freight trains across Indian Railways zones with attractive running allowances.',
      selection_process: JSON.stringify(['CBT-1 (75 Qs - Math, Reasoning, Science, GA)', 'CBT-2 Part A (100 Qs - Merit) + Part B (75 Qs Trade Test Qualifying)', 'Computer Based Aptitude Test (CBAT Psycho Test)', 'Document Verification & A-1 Medical Standard']),
      exam_pattern_summary: 'CBT-1: 60 mins. CBT-2 Part A: 90 mins, Part B: 60 mins. Strict A-1 eyesight standard (6/6 without glasses).',
      official_url: 'https://rrbcdg.gov.in',
      last_verified: '2026-08-23',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 100,
      duration_minutes: 90,
      dates: {
        cycle_name: 'RRB ALP 2026',
        year: 2026,
        notification_date: '2026-01-20',
        application_start: '2026-01-20',
        application_end: '2026-02-19',
        admit_card_date: '2026-10-15',
        exam_date: '2026-11-25',
        result_date: '2027-01-10',
        interview_date: null,
        final_result_date: '2027-05-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_rrb_je',
      code: 'RRB JE',
      name: 'RRB Junior Engineer (Civil, Mechanical, Electrical, Electronics, IT)',
      organization: 'Railway Recruitment Control Board',
      category: 'Railways',
      sub_category: 'Technical Engineering',
      qualification: 'Diploma',
      degree_required: 'Three years Diploma in Civil/Mechanical/Electrical/Electronics/IT or B.E/B.Tech',
      age_min: 18,
      age_max: 33,
      salary_min: 35400,
      salary_max: 112400,
      pay_level: 'Level 6 (7th CPC)',
      in_hand_salary: '₹50,000 - ₹62,000 / month',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Technical',
      state: 'All India',
      description: 'Junior Engineers, Depot Material Superintendents (DMS), and Chemical & Metallurgical Assistants (CMA) across Zonal Railways & Production Units.',
      selection_process: JSON.stringify(['CBT-1 (100 Qs: Math, Reasoning, Science, General Awareness)', 'CBT-2 (150 Qs: Technical Domain Abilities 100 Qs + Physics/Chemistry/Computers/Environment 50 Qs)', 'Document Verification & Medical']),
      exam_pattern_summary: 'CBT-1: 100 Marks (90 mins). CBT-2: 150 Marks (120 mins). Negative: 1/3rd mark.',
      official_url: 'https://rrbcdg.gov.in',
      last_verified: '2026-08-22',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 150,
      duration_minutes: 120,
      dates: {
        cycle_name: 'RRB JE 2026',
        year: 2026,
        notification_date: '2026-07-30',
        application_start: '2026-07-30',
        application_end: '2026-08-29',
        admit_card_date: '2026-11-20',
        exam_date: '2026-12-06',
        result_date: '2027-01-30',
        interview_date: null,
        final_result_date: '2027-04-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_rpf_si',
      code: 'RPF SI',
      name: 'Railway Protection Force Sub-Inspector (RPF SI)',
      organization: 'Ministry of Railways',
      category: 'Railways',
      sub_category: 'Railway Security Uniformed',
      qualification: 'Any Degree',
      degree_required: 'Graduation from a recognized University',
      age_min: 20,
      age_max: 28,
      salary_min: 35400,
      salary_max: 112400,
      pay_level: 'Level 6',
      in_hand_salary: '₹50,000 - ₹60,000 / month',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Police',
      state: 'All India',
      description: 'Executive security and law enforcement cadre protecting railway passengers, passenger areas, and railway infrastructure.',
      selection_process: JSON.stringify(['Computer Based Test (120 Qs - General Awareness, Arithmetic, General Intelligence)', 'Physical Efficiency Test (PET) & Physical Measurement Test (PMT)', 'Document Verification']),
      exam_pattern_summary: '120 Questions (90 Minutes). 50 Marks General Awareness, 35 Marks Arithmetic, 35 Marks Reasoning. Negative: 1/3rd.',
      official_url: 'https://rrbcdg.gov.in',
      last_verified: '2026-08-21',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 120,
      duration_minutes: 90,
      dates: {
        cycle_name: 'RPF SI 2026',
        year: 2026,
        notification_date: '2026-04-15',
        application_start: '2026-04-15',
        application_end: '2026-05-14',
        admit_card_date: '2026-09-01',
        exam_date: '2026-09-18',
        result_date: '2026-11-10',
        interview_date: null,
        final_result_date: '2027-02-15',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 4. BANKING & FINANCIAL INSTITUTIONS
    // ==========================================
    {
      id: 'exam_rbi_grade_b',
      code: 'RBI Grade B',
      name: 'Reserve Bank of India Grade B Officers (General/DEPR/DSIM)',
      organization: 'Reserve Bank of India Services Board',
      category: 'Banking',
      sub_category: 'Central Banking Regulatory Cadre',
      qualification: 'Any Degree',
      degree_required: 'Minimum 60% marks (50% for SC/ST/PwBD) in Graduation or Post Graduation',
      age_min: 21,
      age_max: 30,
      salary_min: 55200,
      salary_max: 185000,
      pay_level: 'Grade B (Executive Manager)',
      in_hand_salary: '₹1,15,000 - ₹1,35,000 / month + Lease Accommodation',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'All India',
      description: 'The pinnacle of banking regulatory careers in India. Formulates monetary policy, bank supervision, and financial regulation.',
      selection_process: JSON.stringify(['Phase-I: Online Objective Test (General Awareness, Reasoning, English, Quant - 200 Marks)', 'Phase-II: Online Descriptive & Objective (Paper-I Economic & Social Issues, Paper-II English Writing Skills, Paper-III Finance & Management)', 'Phase-III: Interview (75 Marks)']),
      exam_pattern_summary: 'Phase-1: 200 Marks (120 mins). Phase-2: 300 Marks (3 Papers of 100 Marks each). Interview: 75 Marks.',
      official_url: 'https://rbi.org.in',
      last_verified: '2026-08-25',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 375,
      duration_minutes: 120,
      dates: {
        cycle_name: 'RBI Grade B 2026',
        year: 2026,
        notification_date: '2026-07-15',
        application_start: '2026-07-15',
        application_end: '2026-08-10',
        admit_card_date: '2026-08-28',
        exam_date: '2026-09-08',
        result_date: '2026-10-15',
        interview_date: '2026-12-05',
        final_result_date: '2027-02-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_sbi_po',
      code: 'SBI PO',
      name: 'State Bank of India Probationary Officer (SBI PO)',
      organization: 'State Bank of India',
      category: 'Banking',
      sub_category: 'Public Sector Commercial Bank',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 21,
      age_max: 30,
      salary_min: 41960,
      salary_max: 135000,
      pay_level: 'Junior Management Grade Scale-I (JMGS-I)',
      in_hand_salary: '₹68,000 - ₹82,000 / month + Leased Accommodation',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'Premier commercial banking leadership recruitment across SBI domestic branches and international operations.',
      selection_process: JSON.stringify(['Phase-I: Preliminary Examination (100 Marks)', 'Phase-II: Main Examination (Objective 200 Marks + Descriptive 50 Marks)', 'Phase-III: Psychometric Test, Group Discussion (20 Marks) & Interview (30 Marks)']),
      exam_pattern_summary: 'Prelims: 100 Qs (1 Hour). Mains: 155 Qs (200 Marks) + 2 Descriptive Qs (50 Marks). GD/Interview: 50 Marks.',
      official_url: 'https://sbi.co.in/careers',
      last_verified: '2026-08-24',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 250,
      duration_minutes: 180,
      dates: {
        cycle_name: 'SBI PO 2026 Cycle',
        year: 2026,
        notification_date: '2026-09-20',
        application_start: '2026-09-20',
        application_end: '2026-10-15',
        admit_card_date: '2026-10-28',
        exam_date: '2026-11-12',
        result_date: '2026-12-15',
        interview_date: '2027-02-05',
        final_result_date: '2027-03-25',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_ibps_po',
      code: 'IBPS PO',
      name: 'IBPS Probationary Officer (CRP PO/MT)',
      organization: 'Institute of Banking Personnel Selection',
      category: 'Banking',
      sub_category: 'Public Sector Banks',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 20,
      age_max: 30,
      salary_min: 36000,
      salary_max: 110000,
      pay_level: 'Scale-I Officer across 11 Participating PSBs',
      in_hand_salary: '₹55,000 - ₹68,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'Combined recruitment for Scale-I Officers in Bank of Baroda, Canara Bank, PNB, Union Bank, Indian Bank, and other public sector banks.',
      selection_process: JSON.stringify(['Phase-I: Preliminary Examination (100 Marks)', 'Phase-II: Main Examination (Objective 200 Marks + Descriptive 25 Marks)', 'Phase-III: Common Interview (100 Marks)']),
      exam_pattern_summary: 'Prelims: 100 Qs (60 mins). Mains: 225 Marks (3.5 hours). Interview: 100 Marks. 80:20 weightage for final merit.',
      official_url: 'https://ibps.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 325,
      duration_minutes: 210,
      dates: {
        cycle_name: 'IBPS PO CRP-XVI',
        year: 2026,
        notification_date: '2026-08-01',
        application_start: '2026-08-01',
        application_end: '2026-08-28',
        admit_card_date: '2026-10-05',
        exam_date: '2026-10-19',
        result_date: '2026-11-25',
        interview_date: '2027-01-20',
        final_result_date: '2027-04-01',
        status: 'Application Open'
      }
    },
    {
      id: 'exam_nabard_grade_a',
      code: 'NABARD Grade A',
      name: 'NABARD Assistant Manager in Grade A (RDBS / Rajbhasha)',
      organization: 'National Bank for Agriculture and Rural Development',
      category: 'Banking',
      sub_category: 'Development Banking',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree with minimum 60% marks (55% for SC/ST/PWBD)',
      age_min: 21,
      age_max: 30,
      salary_min: 44500,
      salary_max: 145000,
      pay_level: 'Grade A (Assistant Manager)',
      in_hand_salary: '₹85,000 - ₹1,00,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'All India',
      description: 'Apex development financial institution in India dedicated to agriculture, rural infrastructure, and rural banking regulation.',
      selection_process: JSON.stringify(['Phase-I: Online Preliminary Exam (200 Marks - Qualifying + Merit Sections: ESI, ARD, GA)', 'Phase-II: Main Exam (Paper 1 General English + Paper 2 Economic & Social Issues and Agri & Rural Dev)', 'Phase-III: Interview (50 Marks)']),
      exam_pattern_summary: 'Phase-1: 200 Qs (120 mins). Phase-2: 200 Marks. Interview: 50 Marks.',
      official_url: 'https://nabard.org',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 250,
      duration_minutes: 120,
      dates: {
        cycle_name: 'NABARD Grade A 2026',
        year: 2026,
        notification_date: '2026-07-25',
        application_start: '2026-07-25',
        application_end: '2026-08-18',
        admit_card_date: '2026-08-30',
        exam_date: '2026-09-12',
        result_date: '2026-10-25',
        interview_date: '2026-12-10',
        final_result_date: '2027-02-15',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 5. DEFENCE & PARAMILITARY SERVICES
    // ==========================================
    {
      id: 'exam_nda',
      code: 'NDA & NA',
      name: 'National Defence Academy & Naval Academy Examination',
      organization: 'Union Public Service Commission',
      category: 'Defence',
      sub_category: 'Tri-Services Officer Cadet (12th Pass)',
      qualification: '12th',
      degree_required: '12th Class pass (Physics and Math mandatory for Air Force and Navy Wings)',
      age_min: 16,
      age_max: 19,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Cadet Stipend ₹56,100/mo -> Lieutenant Rank on Commissioning',
      in_hand_salary: '₹75,000 - ₹95,000 / month + Military Service Pay',
      difficulty: 'hard',
      frequency: 'Bi-annual',
      job_type: 'Uniformed / Defence',
      state: 'All India',
      description: 'Joint services academy training future commissioned officers of Indian Army, Indian Navy, and Indian Air Force.',
      selection_process: JSON.stringify(['Stage 1: Written Examination (Mathematics 300 Marks, General Ability Test 600 Marks)', 'Stage 2: 5-Day SSB Interview (Screening, Psychological Tests, GTO, Interview - 900 Marks)', 'Stage 3: Comprehensive Medical Board']),
      exam_pattern_summary: 'Maths: 120 Qs (300 Marks, 2.5 hrs). GAT: 150 Qs (600 Marks, 2.5 hrs). SSB: 900 Marks. Total: 1800 Marks.',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-25',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 1800,
      duration_minutes: 300,
      dates: {
        cycle_name: 'NDA & NA (I) 2027',
        year: 2027,
        notification_date: '2026-12-10',
        application_start: '2026-12-10',
        application_end: '2026-12-30',
        admit_card_date: '2027-03-25',
        exam_date: '2027-04-12',
        result_date: '2027-05-30',
        interview_date: '2027-08-15',
        final_result_date: '2027-11-30',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_cds',
      code: 'CDS Exam',
      name: 'Combined Defence Services (IMA / INA / AFA / OTA)',
      organization: 'Union Public Service Commission',
      category: 'Defence',
      sub_category: 'Graduate Commissioned Officer',
      qualification: 'Any Degree',
      degree_required: 'Degree for IMA/OTA; Degree in Engineering for INA/AFA',
      age_min: 19,
      age_max: 25,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10 (Lieutenant / Flying Officer / Sub Lieutenant)',
      in_hand_salary: '₹75,000 - ₹95,000 / month + MSP ₹15,500',
      difficulty: 'hard',
      frequency: 'Bi-annual',
      job_type: 'Uniformed / Defence',
      state: 'All India',
      description: 'Officer training entry for Indian Military Academy Dehradun, Indian Naval Academy Ezhimala, Air Force Academy Dundigal, and Officers Training Academy Chennai.',
      selection_process: JSON.stringify(['Written Exam (English 100, GK 100, Elementary Math 100 - OTA candidates appear for English + GK only)', '5-Day Services Selection Board (SSB) Interview', 'Medical Examination']),
      exam_pattern_summary: 'IMA/INA/AFA: 300 Marks (3 Papers of 2 hrs each). OTA: 200 Marks. SSB: 300/200 Marks.',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-24',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 600,
      duration_minutes: 360,
      dates: {
        cycle_name: 'CDS (I) 2027',
        year: 2027,
        notification_date: '2026-12-10',
        application_start: '2026-12-10',
        application_end: '2026-12-30',
        admit_card_date: '2027-03-25',
        exam_date: '2027-04-12',
        result_date: '2027-05-30',
        interview_date: '2027-08-20',
        final_result_date: '2027-11-25',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_afcat',
      code: 'AFCAT',
      name: 'Air Force Common Admission Test (Flying & Ground Duty)',
      organization: 'Indian Air Force',
      category: 'Defence',
      sub_category: 'Air Force Commissioned Officer',
      qualification: 'Any Degree',
      degree_required: 'Graduation (min 60%) + Maths & Physics in 10+2 for Flying; B.E/B.Tech for Technical Branch',
      age_min: 20,
      age_max: 26,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10 (Flying Officer)',
      in_hand_salary: '₹85,000 - ₹1,10,000 / month + Flying Allowance',
      difficulty: 'intermediate',
      frequency: 'Bi-annual',
      job_type: 'Uniformed / Defence',
      state: 'All India',
      description: 'Commissioning into Flying Branch (Fighter, Transport, Helicopter Pilots) and Ground Duty (Technical & Non-Technical) branches of IAF.',
      selection_process: JSON.stringify(['AFCAT Online CBT (General Awareness, Verbal Ability, Numerical Ability, Reasoning - 300 Marks)', 'Air Force Selection Board (AFSB Interview)', 'CPSS (Computerised Pilot Selection System for Flying Branch)', 'Medical Examination']),
      exam_pattern_summary: '100 Questions (300 Marks, 120 mins). Negative: 1 mark for incorrect answer.',
      official_url: 'https://afcat.cdac.in',
      last_verified: '2026-08-22',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 300,
      duration_minutes: 120,
      dates: {
        cycle_name: 'AFCAT 02/2026',
        year: 2026,
        notification_date: '2026-05-30',
        application_start: '2026-06-01',
        application_end: '2026-06-30',
        admit_card_date: '2026-08-10',
        exam_date: '2026-08-23',
        result_date: '2026-09-25',
        interview_date: '2026-11-01',
        final_result_date: '2027-01-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_agniveer_army',
      code: 'Agniveer Army',
      name: 'Indian Army Agniveer Rally Recruitment (GD, Tech, Clerk, Tradesman)',
      organization: 'Indian Army',
      category: 'Defence',
      sub_category: 'Soldier Cadre (Agnipath Scheme)',
      qualification: '10th',
      degree_required: '10th / 12th pass depending on category (GD, Technical, Clerk, Tradesmen)',
      age_min: 17,
      age_max: 21,
      salary_min: 30000,
      salary_max: 40000,
      pay_level: 'Customised Package ₹30,000 to ₹40,000 + Seva Nidhi ₹11.71 Lakhs',
      in_hand_salary: '₹21,000 - ₹28,000 / month (In-hand) + ₹9k-12k Seva Nidhi',
      difficulty: 'beginner',
      frequency: 'Bi-annual',
      job_type: 'Uniformed / Defence',
      state: 'All India',
      description: 'Soldier recruitment under Agnipath scheme with 25% absorption into regular permanent cadre after 4 years.',
      selection_process: JSON.stringify(['Phase-I: Online Common Entrance Exam (CEE)', 'Phase-II: Recruitment Rally (1.6 km Run, Beam, 9ft Ditch, Zig-Zag Balance)', 'Phase-III: Medical Examination']),
      exam_pattern_summary: 'Online CEE: 50 Qs (100 Marks) for GD; 50 Qs (200 Marks) for Technical/Clerk.',
      official_url: 'https://joinindianarmy.nic.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 100,
      duration_minutes: 60,
      dates: {
        cycle_name: 'Agniveer 2026-27 Intake',
        year: 2026,
        notification_date: '2026-02-13',
        application_start: '2026-02-13',
        application_end: '2026-03-22',
        admit_card_date: '2026-04-10',
        exam_date: '2026-04-22',
        result_date: '2026-06-15',
        interview_date: null,
        final_result_date: '2026-10-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_coast_guard',
      code: 'ICG Navik/Yantrik',
      name: 'Indian Coast Guard Navik (General Duty & Domestic Branch) / Yantrik',
      organization: 'Indian Coast Guard',
      category: 'Defence',
      sub_category: 'Maritime Security',
      qualification: '12th',
      degree_required: '10+2 with Maths & Physics (Navik GD); 10th pass (Navik DB); Diploma in Engg (Yantrik)',
      age_min: 18,
      age_max: 22,
      salary_min: 21700,
      salary_max: 69100,
      pay_level: 'Level 3 & Level 5 + Dearness & Ration Allowances',
      in_hand_salary: '₹30,000 - ₹42,000 / month',
      difficulty: 'intermediate',
      frequency: 'Bi-annual',
      job_type: 'Uniformed / Defence',
      state: 'All India',
      description: 'Maritime safety, anti-smuggling, and coastal defense patrols along India’s 7,516 km coastline and Exclusive Economic Zone (EEZ).',
      selection_process: JSON.stringify(['Stage-I: Computer Based Online Examination', 'Stage-II: Physical Fitness Test (1.6 km run in 7 mins, 20 squats, 10 push-ups) & Document Verification', 'Stage-III: Final Medicals at INS Chilka']),
      exam_pattern_summary: 'Section I (Math, Science, English, Reasoning, GK - 60 Marks) + Section II (Physics & Math 12th Level - 50 Marks).',
      official_url: 'https://joinindiancoastguard.cdac.in',
      last_verified: '2026-08-18',
      status: 'Upcoming',
      is_popular: 0,
      is_featured: 0,
      total_marks: 110,
      duration_minutes: 75,
      dates: {
        cycle_name: 'CGEPT 01/2027',
        year: 2027,
        notification_date: '2026-06-12',
        application_start: '2026-06-12',
        application_end: '2026-07-02',
        admit_card_date: '2026-11-05',
        exam_date: '2026-11-20',
        result_date: '2026-12-25',
        interview_date: null,
        final_result_date: '2027-03-30',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 6. STATE PUBLIC SERVICE COMMISSIONS (STATE PSCs)
    // ==========================================
    // --- TAMIL NADU (TNPSC & TNUSRB) ---
    {
      id: 'exam_tnpsc_grp1',
      code: 'TNPSC Group 1',
      name: 'TNPSC Group 1 Combined Civil Services (Deputy Collector / DSP / CTO)',
      organization: 'Tamil Nadu Public Service Commission',
      category: 'State PSC',
      sub_category: 'Tamil Nadu Premier State Administrative Cadre',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 21,
      age_max: 39,
      salary_min: 56100,
      salary_max: 205700,
      pay_level: 'Level 22 (₹56,100 - ₹2,05,700)',
      in_hand_salary: '₹68,000 - ₹85,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'Tamil Nadu',
      description: 'Premier State Administrative Services examination for Deputy Collector, Deputy Superintendent of Police (DSP), Commercial Tax Officer, and District Registrar in Tamil Nadu.',
      selection_process: JSON.stringify(['Stage 1: Preliminary Examination (General Studies 175 Qs + Aptitude 25 Qs - 300 Marks)', 'Stage 2: Main Written Examination (Paper-I Tamil Eligibility Qualifying + Paper-II, III, IV General Studies - 750 Marks)', 'Stage 3: Interview / Oral Test (100 Marks)']),
      exam_pattern_summary: 'Prelims: 200 Qs / 300 Marks (3 Hours). Mains: 3 Merit Papers (250 Marks each = 750) + Interview (100 Marks). Total: 850 Marks.',
      official_url: 'https://tnpsc.gov.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 850,
      duration_minutes: 180,
      dates: {
        cycle_name: 'TNPSC Group 1 2026 Cycle',
        year: 2026,
        notification_date: '2026-03-28',
        application_start: '2026-03-28',
        application_end: '2026-04-27',
        admit_card_date: '2026-07-02',
        exam_date: '2026-07-12',
        result_date: '2026-09-15',
        interview_date: '2026-11-20',
        final_result_date: '2027-01-15',
        status: 'Exam Ongoing'
      }
    },
    {
      id: 'exam_tnpsc_grp2',
      code: 'TNPSC Group 2',
      name: 'TNPSC Group 2 / 2A (Sub-Registrar, Municipal Commissioner, ASO)',
      organization: 'Tamil Nadu Public Service Commission',
      category: 'State PSC',
      sub_category: 'Tamil Nadu State Executive & Non-Executive',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline from a recognized University',
      age_min: 18,
      age_max: 37,
      salary_min: 36900,
      salary_max: 135700,
      pay_level: 'Level 9 to Level 18 (Executive & Non-Executive)',
      in_hand_salary: '₹45,000 - ₹62,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'Tamil Nadu',
      description: 'Recruitment for Sub-Registrar, Municipal Commissioner, Assistant Section Officer (Secretariat), Revenue Assistant, and Senior Inspector of Co-operative Societies.',
      selection_process: JSON.stringify(['Preliminary Examination: General Tamil/English (100 Qs) + General Studies (75 Qs) + Aptitude (25 Qs) = 300 Marks', 'Mains Examination: Paper-I Tamil Eligibility (Qualifying) + Paper-II General Studies (Degree Standard - 300 Marks)', 'Oral Test (Interview for Group 2 Posts) / Direct Merit (Group 2A)']),
      exam_pattern_summary: 'Prelims: 200 Questions (300 Marks, 3 Hours). Mains Paper-II: 300 Marks (3 Hours). Interview: 40 Marks.',
      official_url: 'https://tnpsc.gov.in',
      last_verified: '2026-08-26',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 340,
      duration_minutes: 180,
      dates: {
        cycle_name: 'TNPSC Group 2/2A 2026',
        year: 2026,
        notification_date: '2026-06-20',
        application_start: '2026-06-20',
        application_end: '2026-07-19',
        admit_card_date: '2026-09-15',
        exam_date: '2026-09-28',
        result_date: '2026-12-10',
        interview_date: '2027-02-15',
        final_result_date: '2027-04-20',
        status: 'Application Open'
      }
    },
    {
      id: 'exam_tnpsc_grp4',
      code: 'TNPSC Group 4 & VAO',
      name: 'TNPSC Group 4 & Village Administrative Officer (VAO)',
      organization: 'Tamil Nadu Public Service Commission',
      category: 'State PSC',
      sub_category: 'Tamil Nadu 10th Pass Mega Recruitment',
      qualification: '10th',
      degree_required: 'SSLC / 10th Standard Pass (Typewriting cert for Typist/Steno)',
      age_min: 21,
      age_max: 42,
      salary_min: 19500,
      salary_max: 71900,
      pay_level: 'Level 8 (₹19,500 - ₹71,900)',
      in_hand_salary: '₹26,000 - ₹35,000 / month',
      difficulty: 'beginner',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'Tamil Nadu',
      description: 'The largest single recruitment exam in Tamil Nadu for Village Administrative Officer (VAO), Junior Assistant, Typist, Steno-Typist, and Bill Collector.',
      selection_process: JSON.stringify(['Single Stage Written Objective Examination (200 Questions / 300 Marks)', 'Certificate Verification & Counselling']),
      exam_pattern_summary: 'Part A: General Tamil (SSLC Standard - 100 Qs / 150 Marks). Part B: General Studies (75 Qs) + Aptitude & Mental Ability (25 Qs) = 150 Marks.',
      official_url: 'https://tnpsc.gov.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 300,
      duration_minutes: 180,
      dates: {
        cycle_name: 'TNPSC Group 4 2026',
        year: 2026,
        notification_date: '2026-01-30',
        application_start: '2026-01-30',
        application_end: '2026-02-28',
        admit_card_date: '2026-05-25',
        exam_date: '2026-06-09',
        result_date: '2026-10-30',
        interview_date: null,
        final_result_date: '2026-12-20',
        status: 'Result Out'
      }
    },
    {
      id: 'exam_tnusrb_si',
      code: 'TNUSRB SI',
      name: 'Tamil Nadu Police Sub-Inspector (Taluk, AR & TSP)',
      organization: 'Tamil Nadu Uniformed Services Recruitment Board',
      category: 'State PSC',
      sub_category: 'Tamil Nadu Police Officer Cadre',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any stream',
      age_min: 20,
      age_max: 30,
      salary_min: 36900,
      salary_max: 116600,
      pay_level: 'Level 13',
      in_hand_salary: '₹48,000 - ₹58,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Police',
      state: 'Tamil Nadu',
      description: 'Direct recruitment of Sub-Inspectors of Police in Taluk, Armed Reserve (AR), and Tamil Nadu Special Police (TSP).',
      selection_process: JSON.stringify(['Written Examination Part I (Tamil Eligibility Test - 100 Marks qualifying)', 'Written Examination Part II (General Knowledge & Psychology - 70 Marks)', 'Physical Measurement Test (PMT) & Endurance Test (ET)', 'Physical Efficiency Test (15 Marks - Star ratings)', 'Viva-Voce / Interview (10 Marks)']),
      exam_pattern_summary: 'Written Test (70 Marks) + PET (15 Marks) + Viva (10 Marks) + Special Marks (5 Marks NCC/NSS/Sports) = 100 Marks.',
      official_url: 'https://tnusrb.tn.gov.in',
      last_verified: '2026-08-21',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 100,
      duration_minutes: 150,
      dates: {
        cycle_name: 'TNUSRB SI 2026',
        year: 2026,
        notification_date: '2026-05-05',
        application_start: '2026-05-05',
        application_end: '2026-06-04',
        admit_card_date: '2026-08-10',
        exam_date: '2026-08-26',
        result_date: '2026-10-15',
        interview_date: '2026-12-05',
        final_result_date: '2027-01-25',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_tnusrb_constable',
      code: 'TNUSRB Constable',
      name: 'Tamil Nadu Police Constable, Jail Warder & Fireman',
      organization: 'Tamil Nadu Uniformed Services Recruitment Board',
      category: 'State PSC',
      sub_category: 'Tamil Nadu Police 10th Pass',
      qualification: '10th',
      degree_required: '10th Standard Pass (SSLC) with Tamil language subject',
      age_min: 18,
      age_max: 26,
      salary_min: 18200,
      salary_max: 67100,
      pay_level: 'Level 6',
      in_hand_salary: '₹26,000 - ₹34,000 / month',
      difficulty: 'beginner',
      frequency: 'Annual',
      job_type: 'Police',
      state: 'Tamil Nadu',
      description: 'Recruitment for Grade-II Police Constable (Armed Reserve & Special Police), Grade-II Jail Warder, and Fireman.',
      selection_process: JSON.stringify(['Written Exam Part-1 (Tamil Eligibility - 80 Qs)', 'Written Exam Part-2 (Main Exam GK 45 Qs + Psychology 25 Qs = 70 Marks)', 'PMT / Endurance Test & Physical Efficiency Test (24 Marks)', 'Certificate Verification']),
      exam_pattern_summary: 'Written Exam: 70 Marks + PET: 24 Marks + Special Marks: 6 Marks = Total 100 Marks.',
      official_url: 'https://tnusrb.tn.gov.in',
      last_verified: '2026-08-19',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 100,
      duration_minutes: 160,
      dates: {
        cycle_name: 'TN Police Constable 2026',
        year: 2026,
        notification_date: '2026-08-15',
        application_start: '2026-08-15',
        application_end: '2026-09-15',
        admit_card_date: '2026-11-15',
        exam_date: '2026-12-10',
        result_date: '2027-01-20',
        interview_date: null,
        final_result_date: '2027-04-10',
        status: 'Upcoming'
      }
    },

    // --- OTHER MAJOR STATE PSCs ---
    {
      id: 'exam_kpsc_kas',
      code: 'KPSC KAS',
      name: 'Karnataka Gazetted Probationers (KAS - Assistant Commissioner / DSP)',
      organization: 'Karnataka Public Service Commission',
      category: 'State PSC',
      sub_category: 'Karnataka State Services',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 21,
      age_max: 38,
      salary_min: 52650,
      salary_max: 97100,
      pay_level: 'Group A / Group B Gazetted',
      in_hand_salary: '₹65,000 - ₹82,000 / month',
      difficulty: 'hard',
      frequency: 'Periodic',
      job_type: 'Administrative',
      state: 'Karnataka',
      description: 'Karnataka state civil services recruitment for Assistant Commissioner, DSP, Tehsildar, and Commercial Tax Officer.',
      selection_process: JSON.stringify(['Prelims: Paper-1 GS & Humanities + Paper-2 GS, Science, Aptitude (400 Marks)', 'Mains: 4 General Studies Papers + 2 Compulsory Language Papers Kannada/English (1250 Marks)', 'Personality Test / Interview (50 Marks)']),
      exam_pattern_summary: 'Prelims (400 Marks) -> Mains (1250 Marks) -> Interview (50 Marks).',
      official_url: 'https://kpsc.kar.nic.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 1300,
      duration_minutes: 180,
      dates: {
        cycle_name: 'KPSC Gazetted 2026',
        year: 2026,
        notification_date: '2026-02-27',
        application_start: '2026-02-27',
        application_end: '2026-03-28',
        admit_card_date: '2026-08-15',
        exam_date: '2026-08-27',
        result_date: '2026-10-30',
        interview_date: '2027-01-15',
        final_result_date: '2027-04-10',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_uppsc_pcs',
      code: 'UPPSC PCS',
      name: 'UPPSC Combined State / Upper Subordinate Services (PCS)',
      organization: 'Uttar Pradesh Public Service Commission',
      category: 'State PSC',
      sub_category: 'Uttar Pradesh State Civil Services',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any stream from recognized University',
      age_min: 21,
      age_max: 40,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Pay Matrix Level 10 (SDM, Dy SP, ARTO, BDO)',
      in_hand_salary: '₹65,000 - ₹85,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'Uttar Pradesh',
      description: 'Sub-Divisional Magistrate (SDM), Deputy SP, Block Development Officer, and Naib Tehsildar across Uttar Pradesh.',
      selection_process: JSON.stringify(['Prelims (Paper-1 GS + Paper-2 CSAT Qualifying)', 'Mains (General Hindi 150, Essay 150, GS Papers 1 to 6 - Total 1500 Marks)', 'Personality Test / Interview (100 Marks)']),
      exam_pattern_summary: 'Prelims: 400 Marks. Mains: 1500 Marks (6 GS Papers including UP Special Papers 5 & 6). Interview: 100 Marks.',
      official_url: 'https://uppsc.up.nic.in',
      last_verified: '2026-08-24',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 1600,
      duration_minutes: 180,
      dates: {
        cycle_name: 'UPPSC PCS 2026',
        year: 2026,
        notification_date: '2026-01-01',
        application_start: '2026-01-01',
        application_end: '2026-02-02',
        admit_card_date: '2026-10-15',
        exam_date: '2026-10-27',
        result_date: '2026-12-15',
        interview_date: '2027-02-20',
        final_result_date: '2027-05-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_appsc_grp1',
      code: 'APPSC Group 1',
      name: 'APPSC Group 1 Services (Deputy Collector / DSP / CTO)',
      organization: 'Andhra Pradesh Public Service Commission',
      category: 'State PSC',
      sub_category: 'Andhra Pradesh State Civil Services',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 18,
      age_max: 42,
      salary_min: 54060,
      salary_max: 133900,
      pay_level: 'Group 1 Gazetted',
      in_hand_salary: '₹65,000 - ₹80,000 / month',
      difficulty: 'hard',
      frequency: 'Periodic',
      job_type: 'Administrative',
      state: 'Andhra Pradesh',
      description: 'Andhra Pradesh state administrative leadership recruitment.',
      selection_process: JSON.stringify(['Screening Test / Prelims (Paper-1 GS + Paper-2 General Aptitude - 240 Marks)', 'Mains (English & Telugu Qualifying + 5 Merit Papers - 750 Marks)', 'Interview / Oral Test (75 Marks)']),
      exam_pattern_summary: 'Prelims: 240 Marks. Mains: 750 Marks (5 Papers of 150 Marks each). Interview: 75 Marks.',
      official_url: 'https://psc.ap.gov.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 825,
      duration_minutes: 150,
      dates: {
        cycle_name: 'APPSC Group 1 2026',
        year: 2026,
        notification_date: '2026-01-08',
        application_start: '2026-01-08',
        application_end: '2026-01-28',
        admit_card_date: '2026-03-10',
        exam_date: '2026-03-17',
        result_date: '2026-05-15',
        interview_date: '2026-09-20',
        final_result_date: '2026-12-10',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_tspsc_grp1',
      code: 'TSPSC Group 1',
      name: 'TSPSC Group 1 Services (Deputy Collector / DSP / RDO)',
      organization: 'Telangana State Public Service Commission',
      category: 'State PSC',
      sub_category: 'Telangana State Civil Services',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any stream',
      age_min: 18,
      age_max: 46,
      salary_min: 54220,
      salary_max: 133630,
      pay_level: 'Group 1 Gazetted',
      in_hand_salary: '₹65,000 - ₹82,000 / month',
      difficulty: 'hard',
      frequency: 'Periodic',
      job_type: 'Administrative',
      state: 'Telangana',
      description: 'Telangana State Civil Services recruitment for RDO, DSP, Commercial Tax Officer, and Municipal Commissioner.',
      selection_process: JSON.stringify(['Preliminary Test (General Studies & Mental Ability - 150 Marks)', 'Main Examination (General English Qualifying + 6 Descriptive Papers - 900 Marks - No Interview)']),
      exam_pattern_summary: 'Prelims: 150 Qs / 150 Marks. Mains: 6 Papers of 150 Marks each = 900 Marks. Final selection based 100% on Mains merit.',
      official_url: 'https://tspsc.gov.in',
      last_verified: '2026-08-21',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 900,
      duration_minutes: 180,
      dates: {
        cycle_name: 'TSPSC Group 1 2026',
        year: 2026,
        notification_date: '2026-02-19',
        application_start: '2026-02-23',
        application_end: '2026-03-14',
        admit_card_date: '2026-06-01',
        exam_date: '2026-06-09',
        result_date: '2026-08-20',
        interview_date: null,
        final_result_date: '2027-01-30',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_kerala_psc_kas',
      code: 'Kerala PSC KAS',
      name: 'Kerala Administrative Service (KAS Junior Time Scale)',
      organization: 'Kerala Public Service Commission',
      category: 'State PSC',
      sub_category: 'Kerala State Civil Services',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 21,
      age_max: 32,
      salary_min: 55200,
      salary_max: 115300,
      pay_level: 'Junior Time Scale (KAS)',
      in_hand_salary: '₹62,000 - ₹78,000 / month',
      difficulty: 'hard',
      frequency: 'Periodic',
      job_type: 'Administrative',
      state: 'Kerala',
      description: 'Second gazetted cadre created in Kerala to build a modern managerial leadership stream.',
      selection_process: JSON.stringify(['Preliminary Examination (Paper-I GS & Language + Paper-II GS & Reasoning - 200 Marks)', 'Main Examination (3 Descriptive Papers of 100 Marks each = 300 Marks)', 'Interview (50 Marks)']),
      exam_pattern_summary: 'Prelims: 200 Marks. Mains: 300 Marks. Interview: 50 Marks. Total: 350 Marks.',
      official_url: 'https://keralapsc.gov.in',
      last_verified: '2026-08-19',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 350,
      duration_minutes: 120,
      dates: {
        cycle_name: 'Kerala KAS 2026',
        year: 2026,
        notification_date: '2026-05-15',
        application_start: '2026-05-15',
        application_end: '2026-06-15',
        admit_card_date: '2026-09-20',
        exam_date: '2026-10-10',
        result_date: '2026-12-10',
        interview_date: '2027-02-15',
        final_result_date: '2027-04-30',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_mpsc_rajyaseva',
      code: 'MPSC Rajyaseva',
      name: 'MPSC State Services Examination (Deputy Collector / Dy SP / Tehsildar)',
      organization: 'Maharashtra Public Service Commission',
      category: 'State PSC',
      sub_category: 'Maharashtra Civil Services',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 19,
      age_max: 38,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Group A / Group B',
      in_hand_salary: '₹65,000 - ₹85,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'Maharashtra',
      description: 'Recruitment to Class-1 & Class-2 administrative and executive cadres of the Maharashtra Government.',
      selection_process: JSON.stringify(['Prelims (Paper-1 GS 200 Marks + Paper-2 CSAT Qualifying 200 Marks)', 'Mains (Descriptive UPSC-pattern: 7 Papers - Total 1750 Marks)', 'Personality Test / Interview (275 Marks)']),
      exam_pattern_summary: 'Mains: 1750 Marks + Interview: 275 Marks = 2025 Marks total.',
      official_url: 'https://mpsc.gov.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 2025,
      duration_minutes: 120,
      dates: {
        cycle_name: 'MPSC Civil Services 2026',
        year: 2026,
        notification_date: '2026-01-05',
        application_start: '2026-01-05',
        application_end: '2026-01-25',
        admit_card_date: '2026-07-10',
        exam_date: '2026-07-21',
        result_date: '2026-09-30',
        interview_date: '2026-12-15',
        final_result_date: '2027-03-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_bpsc_cce',
      code: 'BPSC CCE',
      name: 'BPSC Combined Competitive Examination (SDM, DSP, BPRO, Revenue Officer)',
      organization: 'Bihar Public Service Commission',
      category: 'State PSC',
      sub_category: 'Bihar State Civil Services',
      qualification: 'Any Degree',
      degree_required: 'Graduation in any discipline',
      age_min: 20,
      age_max: 37,
      salary_min: 53100,
      salary_max: 167800,
      pay_level: 'Level 9 (SDM/DSP) & Level 7',
      in_hand_salary: '₹62,000 - ₹78,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Administrative',
      state: 'Bihar',
      description: 'Bihar state administrative services officer recruitment.',
      selection_process: JSON.stringify(['Prelims: General Studies (150 Qs / 150 Marks with 1/3rd Negative Marking)', 'Mains: General Hindi (Qualifying 100 Marks) + GS-1 (300) + GS-2 (300) + Essay (300) = 900 Marks', 'Interview / Personality Test (120 Marks)']),
      exam_pattern_summary: 'Prelims: 150 Marks. Mains: 900 Marks. Interview: 120 Marks. Final Merit: 1020 Marks.',
      official_url: 'https://bpsc.bih.nic.in',
      last_verified: '2026-08-21',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 1020,
      duration_minutes: 120,
      dates: {
        cycle_name: '71st BPSC CCE 2026',
        year: 2026,
        notification_date: '2026-07-15',
        application_start: '2026-07-15',
        application_end: '2026-08-15',
        admit_card_date: '2026-09-18',
        exam_date: '2026-09-30',
        result_date: '2026-11-20',
        interview_date: '2027-02-10',
        final_result_date: '2027-04-25',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 7. TEACHING & ACADEMIC RECRUITMENT
    // ==========================================
    {
      id: 'exam_ctet',
      code: 'CTET',
      name: 'Central Teacher Eligibility Test (CTET Paper-I & Paper-II)',
      organization: 'Central Board of Secondary Education (CBSE)',
      category: 'Teaching',
      sub_category: 'Central School Teacher Certification',
      qualification: 'Diploma',
      degree_required: 'D.El.Ed / B.El.Ed for Paper-I; B.Ed / D.El.Ed for Paper-II',
      age_min: 18,
      age_max: 45,
      salary_min: 35400,
      salary_max: 112400,
      pay_level: 'Eligibility for KVS, NVS, DSSSB, Central Tibetan Schools',
      in_hand_salary: '₹42,000 - ₹58,000 / month (on appointment)',
      difficulty: 'intermediate',
      frequency: 'Bi-annual',
      job_type: 'Teaching',
      state: 'All India',
      description: 'Mandatory national teacher eligibility certification for Primary (Class I-V) and Upper Primary (Class VI-VIII) government school appointments.',
      selection_process: JSON.stringify(['Paper-I (For Classes I-V): Child Development & Pedagogy, Language I & II, Mathematics, Environmental Studies (150 Marks)', 'Paper-II (For Classes VI-VIII): Child Development, Language I & II, Mathematics & Science or Social Studies (150 Marks)']),
      exam_pattern_summary: '150 MCQs / 150 Marks (150 Minutes). No Negative Marking. 60% (90/150) qualifying score.',
      official_url: 'https://ctet.nic.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 150,
      duration_minutes: 150,
      dates: {
        cycle_name: 'CTET December 2026',
        year: 2026,
        notification_date: '2026-09-17',
        application_start: '2026-09-17',
        application_end: '2026-10-16',
        admit_card_date: '2026-11-28',
        exam_date: '2026-12-14',
        result_date: '2027-01-20',
        interview_date: null,
        final_result_date: '2027-01-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_ugc_net',
      code: 'UGC NET',
      name: 'UGC National Eligibility Test (Assistant Professor & JRF)',
      organization: 'National Testing Agency (NTA)',
      category: 'Teaching',
      sub_category: 'Higher Education & Research Fellowship',
      qualification: 'Postgraduate',
      degree_required: 'Master Degree with at least 55% marks (50% for OBC/SC/ST/PwD)',
      age_min: 21,
      age_max: 30,
      salary_min: 57700,
      salary_max: 182400,
      pay_level: 'Academic Level 10 (Assistant Professor) / JRF Fellowship ₹37,000/mo',
      in_hand_salary: '₹75,000 - ₹95,000 / month (Assistant Professor)',
      difficulty: 'hard',
      frequency: 'Bi-annual',
      job_type: 'Teaching',
      state: 'All India',
      description: 'Determines eligibility for Indian nationals for Junior Research Fellowship (JRF) and Assistant Professorship in Indian Universities & Colleges.',
      selection_process: JSON.stringify(['Paper-I: Teaching & Research Aptitude, Reasoning, Comprehension, Higher Education System (50 Qs / 100 Marks)', 'Paper-II: Domain Subject Chosen by Candidate (100 Qs / 200 Marks)']),
      exam_pattern_summary: '150 Questions (300 Marks, 3 Hours, single shift, no break). No Negative Marking.',
      official_url: 'https://ugcnet.nta.ac.in',
      last_verified: '2026-08-23',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 300,
      duration_minutes: 180,
      dates: {
        cycle_name: 'UGC NET Dec 2026',
        year: 2026,
        notification_date: '2026-10-01',
        application_start: '2026-10-01',
        application_end: '2026-10-31',
        admit_card_date: '2026-12-01',
        exam_date: '2026-12-15',
        result_date: '2027-01-25',
        interview_date: null,
        final_result_date: '2027-01-25',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_kvs_recruitment',
      code: 'KVS Teacher',
      name: 'Kendriya Vidyalaya Sangathan PGT, TGT & PRT Recruitment',
      organization: 'Kendriya Vidyalaya Sangathan (HQ)',
      category: 'Teaching',
      sub_category: 'Central Government School Teachers',
      qualification: 'Any Degree',
      degree_required: 'B.Ed + CTET Paper-I/II (for PRT/TGT); Post Graduation + B.Ed (for PGT)',
      age_min: 18,
      age_max: 40,
      salary_min: 35400,
      salary_max: 151100,
      pay_level: 'Level 6 (PRT), Level 7 (TGT), Level 8 (PGT)',
      in_hand_salary: '₹48,000 - ₹72,000 / month',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Teaching',
      state: 'All India',
      description: 'Teaching cadre appointments across 1,250+ Kendriya Vidyalayas in India and abroad.',
      selection_process: JSON.stringify(['Computer Based Written Test (180 Marks: General English, Hindi, GK, Reasoning, Computer, Perspectives on Education, Subject Specific)', 'Professional Competency Test (Demo Teaching 30 Marks + Interview 30 Marks = 60 Marks)', 'Final Merit (70% Written + 30% Interview/Demo)']),
      exam_pattern_summary: '180 Qs / 180 Marks (180 Minutes). Merit weightage: 70:30.',
      official_url: 'https://kvsangathan.nic.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 180,
      duration_minutes: 180,
      dates: {
        cycle_name: 'KVS Direct Recruitment 2026',
        year: 2026,
        notification_date: '2026-08-10',
        application_start: '2026-08-10',
        application_end: '2026-09-05',
        admit_card_date: '2026-11-10',
        exam_date: '2026-11-28',
        result_date: '2027-01-15',
        interview_date: '2027-03-10',
        final_result_date: '2027-05-20',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 8. TECHNICAL & ENGINEERING RECRUITMENT
    // ==========================================
    {
      id: 'exam_gate',
      code: 'GATE',
      name: 'Graduate Aptitude Test in Engineering (GATE / PSU Entry)',
      organization: 'IITs & IISc Bangalore (National Coordinating Board)',
      category: 'Technical',
      sub_category: 'Postgraduate & Maharatna PSU Recruitment',
      qualification: 'B.E/B.Tech',
      degree_required: 'Currently studying in 3rd/4th year or completed B.E/B.Tech/B.Arch/B.Sc Research',
      age_min: 18,
      age_max: 35,
      salary_min: 60000,
      salary_max: 180000,
      pay_level: 'E-2 Grade in PSUs (IOCL, ONGC, NTPC, BHEL, PowerGrid)',
      in_hand_salary: '₹80,000 - ₹1,20,000 / month (in PSUs)',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Technical',
      state: 'All India',
      description: 'The master gateway for M.Tech admissions at IITs/IISc and direct Executive Trainee recruitment across Indian Maharatna/Navratna PSUs.',
      selection_process: JSON.stringify(['Computer Based Test (65 Questions / 100 Marks: General Aptitude 15 Marks + Engg Math & Core Subject 85 Marks)', 'Direct PSU Shortlisting based on GATE Score -> Group Task & Personal Interview']),
      exam_pattern_summary: '65 Questions (100 Marks, 3 Hours). MCQs (Negative marking 1/3rd or 2/3rd) + MSQs + Numerical Answer Type (NAT - No Negative).',
      official_url: 'https://gate2026.iit.ac.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 100,
      duration_minutes: 180,
      dates: {
        cycle_name: 'GATE 2027',
        year: 2027,
        notification_date: '2026-08-24',
        application_start: '2026-08-28',
        application_end: '2026-09-26',
        admit_card_date: '2027-01-03',
        exam_date: '2027-02-06',
        result_date: '2027-03-19',
        interview_date: null,
        final_result_date: '2027-03-19',
        status: 'Application Open'
      }
    },
    {
      id: 'exam_isro_sc',
      code: 'ISRO Scientist/Engineer',
      name: 'ISRO Centralised Recruitment Board (ICRB - Scientist/Engineer SC)',
      organization: 'Indian Space Research Organisation',
      category: 'Technical',
      sub_category: 'Space Research & Rocketry Engineering',
      qualification: 'B.E/B.Tech',
      degree_required: 'B.E/B.Tech in First Class with an aggregate minimum of 65% marks or CGPA 6.84/10',
      age_min: 21,
      age_max: 28,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10 (Scientist/Engineer SC)',
      in_hand_salary: '₹78,000 - ₹95,000 / month + Space Allowances',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Technical',
      state: 'All India',
      description: 'Core scientific career designing launch vehicles (LVM3, PSLV), satellites, propulsion systems, and lunar/planetary exploration probes.',
      selection_process: JSON.stringify(['Written Test (Part A: 80 Qs Core Discipline + Part B: 15 Qs General Aptitude)', 'Personal Interview (Minimum 60/100 marks to qualify)']),
      exam_pattern_summary: 'Written Test: 100 Marks (120 mins, 1/3rd negative). Interview weightage: 50% Written + 50% Interview.',
      official_url: 'https://isro.gov.in/careers',
      last_verified: '2026-08-24',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 200,
      duration_minutes: 120,
      dates: {
        cycle_name: 'ISRO ICRB 2026',
        year: 2026,
        notification_date: '2026-05-25',
        application_start: '2026-05-25',
        application_end: '2026-06-14',
        admit_card_date: '2026-11-10',
        exam_date: '2026-11-29',
        result_date: '2027-01-15',
        interview_date: '2027-03-20',
        final_result_date: '2027-05-10',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_drdo_ceptam',
      code: 'DRDO CEPTAM',
      name: 'DRDO Scientist B (RAC) & Senior Technical Assistant (CEPTAM)',
      organization: 'Defence Research & Development Organisation',
      category: 'Technical',
      sub_category: 'Defence Tech & R&D',
      qualification: 'B.E/B.Tech',
      degree_required: 'First Class Bachelor Degree in Engineering or Technology',
      age_min: 18,
      age_max: 28,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Level 10 (Scientist B) / Level 6 (STA-B)',
      in_hand_salary: '₹75,000 - ₹95,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Technical',
      state: 'All India',
      description: 'Research and development of defense missiles (Agni, BrahMos), radar systems, combat avionics, and naval systems.',
      selection_process: JSON.stringify(['Shortlisting based on GATE Score', 'Descriptive Written Examination (for specific disciplines)', 'Personal Interview at RAC New Delhi']),
      exam_pattern_summary: '80% GATE Score / Written Test + 20% Personal Interview.',
      official_url: 'https://rac.gov.in',
      last_verified: '2026-08-22',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 100,
      duration_minutes: 180,
      dates: {
        cycle_name: 'DRDO RAC 2026',
        year: 2026,
        notification_date: '2026-06-05',
        application_start: '2026-06-05',
        application_end: '2026-06-28',
        admit_card_date: '2026-09-15',
        exam_date: '2026-10-10',
        result_date: '2026-11-30',
        interview_date: '2027-01-15',
        final_result_date: '2027-03-30',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_barc_oces',
      code: 'BARC OCES',
      name: 'Bhabha Atomic Research Centre Scientific Officers (OCES/DGFS)',
      organization: 'Bhabha Atomic Research Centre (DAE)',
      category: 'Technical',
      sub_category: 'Nuclear Science & Engineering',
      qualification: 'B.E/B.Tech',
      degree_required: 'B.E/B.Tech/B.Sc (Engg) with minimum 60% aggregate marks',
      age_min: 18,
      age_max: 26,
      salary_min: 56100,
      salary_max: 177500,
      pay_level: 'Scientific Officer (C) Level 10',
      in_hand_salary: '₹85,000 - ₹1,05,000 / month',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Technical',
      state: 'All India',
      description: 'Nuclear energy reactors, radiation technology, and strategic scientific research under Department of Atomic Energy.',
      selection_process: JSON.stringify(['Shortlisting via BARC Online Screening Exam or valid GATE Score', 'Rigorous Technical Personal Interview (BARC Mumbai)']),
      exam_pattern_summary: 'Online Exam: 100 Qs (300 Marks, 120 mins). Interview is purely technical conceptual testing.',
      official_url: 'https://barconlineexam.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 300,
      duration_minutes: 120,
      dates: {
        cycle_name: 'BARC OCES 2026',
        year: 2026,
        notification_date: '2026-01-05',
        application_start: '2026-01-05',
        application_end: '2026-02-05',
        admit_card_date: '2026-03-01',
        exam_date: '2026-03-16',
        result_date: '2026-04-20',
        interview_date: '2026-06-10',
        final_result_date: '2026-08-15',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 9. INSURANCE & PUBLIC FINANCE
    // ==========================================
    {
      id: 'exam_lic_aao',
      code: 'LIC AAO',
      name: 'Life Insurance Corporation Assistant Administrative Officer (Generalist)',
      organization: 'Life Insurance Corporation of India',
      category: 'Insurance',
      sub_category: 'Public Sector Insurance Cadre',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any discipline from a recognized Indian University',
      age_min: 21,
      age_max: 30,
      salary_min: 53600,
      salary_max: 165000,
      pay_level: 'Assistant Administrative Officer (Scale-I)',
      in_hand_salary: '₹75,000 - ₹92,000 / month',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'Executive management across underwriting, policy servicing, investment operations, and claims management in LIC.',
      selection_process: JSON.stringify(['Phase-I: Preliminary Examination (100 Qs - Reasoning, Quant, English)', 'Phase-II: Main Examination (Objective 300 Marks + Descriptive 25 Marks)', 'Phase-III: Interview (60 Marks)', 'Pre-Recruitment Medical Examination']),
      exam_pattern_summary: 'Prelims: 100 Marks (1 hr). Mains: 300 Marks (120 Qs) + Descriptive 25 Marks. Interview: 60 Marks.',
      official_url: 'https://licindia.in',
      last_verified: '2026-08-22',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 385,
      duration_minutes: 180,
      dates: {
        cycle_name: 'LIC AAO 2026',
        year: 2026,
        notification_date: '2026-01-15',
        application_start: '2026-01-15',
        application_end: '2026-01-31',
        admit_card_date: '2026-02-10',
        exam_date: '2026-02-20',
        result_date: '2026-03-25',
        interview_date: '2026-05-10',
        final_result_date: '2026-07-15',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_epfo_eo_ao',
      code: 'UPSC EPFO EO/AO',
      name: 'EPFO Enforcement Officer / Accounts Officer & APFC',
      organization: 'Union Public Service Commission',
      category: 'Insurance',
      sub_category: 'Social Security & Labor Law Regulation',
      qualification: 'Any Degree',
      degree_required: 'Bachelor degree in any subject (Desirable: Law, MBA Finance, CA)',
      age_min: 18,
      age_max: 35,
      salary_min: 47600,
      salary_max: 151100,
      pay_level: 'Level 8 (EO/AO) & Level 10 (APFC)',
      in_hand_salary: '₹68,000 - ₹85,000 / month',
      difficulty: 'hard',
      frequency: 'Periodic',
      job_type: 'Administrative',
      state: 'All India',
      description: 'Enforcing statutory compliance under the Employees Provident Fund and Miscellaneous Provisions Act, 1952.',
      selection_process: JSON.stringify(['Recruitment Test (RT - Objective: General English, Indian Freedom Struggle, Current Events, Indian Polity & Economy, General Accounting Principles, Industrial Relations & Labor Laws, Social Security in India, General Science, Math)', 'Personal Interview (100 Marks)', 'Final Selection: 75% Weightage RT + 25% Weightage Interview']),
      exam_pattern_summary: 'Recruitment Test: 120 Questions (300 Marks, 2 Hours, 1/3rd Negative). Interview: 100 Marks.',
      official_url: 'https://upsc.gov.in',
      last_verified: '2026-08-23',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 400,
      duration_minutes: 120,
      dates: {
        cycle_name: 'EPFO EO/AO 2026',
        year: 2026,
        notification_date: '2026-02-25',
        application_start: '2026-02-25',
        application_end: '2026-03-17',
        admit_card_date: '2026-06-15',
        exam_date: '2026-07-02',
        result_date: '2026-08-25',
        interview_date: '2026-11-10',
        final_result_date: '2027-01-20',
        status: 'Upcoming'
      }
    },
    {
      id: 'exam_niacl_ao',
      code: 'NIACL AO',
      name: 'New India Assurance Administrative Officer (Generalist & Specialist)',
      organization: 'The New India Assurance Company Ltd',
      category: 'Insurance',
      sub_category: 'General Insurance Public Sector',
      qualification: 'Any Degree',
      degree_required: 'Graduation with min 60% marks (55% for SC/ST/PwBD)',
      age_min: 21,
      age_max: 30,
      salary_min: 50925,
      salary_max: 155000,
      pay_level: 'Scale-I Officer',
      in_hand_salary: '₹70,000 - ₹85,000 / month',
      difficulty: 'intermediate',
      frequency: 'Annual',
      job_type: 'Non-Technical',
      state: 'All India',
      description: 'Officer cadre in India’s largest public-sector general insurance company.',
      selection_process: JSON.stringify(['Phase-I: Preliminary Exam (100 Qs - 100 Marks)', 'Phase-II: Main Exam (Objective 200 Marks + Descriptive 30 Marks)', 'Phase-III: Interview (50 Marks)']),
      exam_pattern_summary: 'Prelims: 100 Marks (1 Hr). Mains: 230 Marks. Interview: 50 Marks.',
      official_url: 'https://newindia.co.in',
      last_verified: '2026-08-21',
      status: 'Upcoming',
      is_popular: 0,
      is_featured: 0,
      total_marks: 280,
      duration_minutes: 150,
      dates: {
        cycle_name: 'NIACL AO 2026',
        year: 2026,
        notification_date: '2026-08-01',
        application_start: '2026-08-01',
        application_end: '2026-08-21',
        admit_card_date: '2026-09-05',
        exam_date: '2026-09-14',
        result_date: '2026-10-20',
        interview_date: '2026-12-15',
        final_result_date: '2027-02-10',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 10. JUDICIARY & LEGAL SERVICES
    // ==========================================
    {
      id: 'exam_civil_judge',
      code: 'Civil Judge (JD)',
      name: 'Judicial Service Examination (Civil Judge Junior Division / JMFC)',
      organization: 'High Courts of Respective States / State PSC',
      category: 'Judiciary',
      sub_category: 'Subordinate Judiciary Judicial Officers',
      qualification: 'Law Degree',
      degree_required: 'Degree in Law (LL.B 3 Years or 5 Years Integrated) from recognized Bar Council of India institution',
      age_min: 21,
      age_max: 35,
      salary_min: 77840,
      salary_max: 136520,
      pay_level: 'Junior Civil Judge (First National Judicial Pay Commission)',
      in_hand_salary: '₹85,000 - ₹1,10,000 / month + Judicial Allowances',
      difficulty: 'hard',
      frequency: 'Annual',
      job_type: 'Judicial',
      state: 'All India',
      description: 'Presiding judicial officer in Civil Courts (Junior Division) and Judicial Magistrate First Class (JMFC) criminal courts.',
      selection_process: JSON.stringify(['Preliminary Examination (Objective Law, CrPC, CPC, IPC/BNS, Evidence, Constitution & Local Acts)', 'Main Written Examination (4 to 5 Descriptive Papers: Civil Law-1, Civil Law-2, Criminal Law, Judgment Writing & Language)', 'Viva-Voce / Personal Interview']),
      exam_pattern_summary: 'Prelims: 100-150 Marks. Mains: 400-500 Marks (Subjective Judgment drafting). Interview: 50-100 Marks.',
      official_url: 'https://sci.gov.in',
      last_verified: '2026-08-24',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 1,
      total_marks: 550,
      duration_minutes: 180,
      dates: {
        cycle_name: 'Judicial Services 2026',
        year: 2026,
        notification_date: '2026-04-10',
        application_start: '2026-04-10',
        application_end: '2026-05-10',
        admit_card_date: '2026-06-25',
        exam_date: '2026-07-15',
        result_date: '2026-09-10',
        interview_date: '2026-11-25',
        final_result_date: '2027-02-15',
        status: 'Upcoming'
      }
    },

    // ==========================================
    // 11. HEALTHCARE & MEDICAL RECRUITMENT
    // ==========================================
    {
      id: 'exam_aiims_norcet',
      code: 'AIIMS NORCET',
      name: 'AIIMS Nursing Officer Recruitment Common Eligibility Test (NORCET)',
      organization: 'All India Institute of Medical Sciences (AIIMS New Delhi)',
      category: 'Healthcare',
      sub_category: 'Central Institute Healthcare Officers',
      qualification: 'MBBS / Nursing',
      degree_required: 'B.Sc (Hons) Nursing / B.Sc Nursing or GNM with 2 years 50-bedded hospital experience',
      age_min: 18,
      age_max: 30,
      salary_min: 44900,
      salary_max: 142400,
      pay_level: 'Level 7 (₹44,900 - ₹1,42,400)',
      in_hand_salary: '₹62,000 - ₹75,000 / month',
      difficulty: 'intermediate',
      frequency: 'Bi-annual',
      job_type: 'Medical',
      state: 'All India',
      description: 'Recruitment of Nursing Officers in AIIMS New Delhi, all new AIIMS institutions across India, and 4 Central Government Hospitals.',
      selection_process: JSON.stringify(['Stage-I: NORCET Preliminary Examination (100 Qs: 20 General & 80 Nursing Subject)', 'Stage-II: NORCET Main Examination (100 Qs: Practical Clinical Scenario Based)', 'Document Verification & Institute Allocation']),
      exam_pattern_summary: 'Stage-1 (100 Qs, 90 mins, 1/3rd negative) -> Stage-2 (100 Qs, 90 mins).',
      official_url: 'https://aiimsexams.ac.in',
      last_verified: '2026-08-25',
      status: 'Ongoing',
      is_popular: 1,
      is_featured: 1,
      total_marks: 100,
      duration_minutes: 90,
      dates: {
        cycle_name: 'NORCET-7 2026',
        year: 2026,
        notification_date: '2026-08-01',
        application_start: '2026-08-01',
        application_end: '2026-08-21',
        admit_card_date: '2026-09-08',
        exam_date: '2026-09-15',
        result_date: '2026-10-10',
        interview_date: null,
        final_result_date: '2026-10-30',
        status: 'Application Open'
      }
    },
    {
      id: 'exam_esic_nursing',
      code: 'ESIC Staff Nurse',
      name: 'Employees State Insurance Corporation (ESIC) Nursing & Paramedical Cadre',
      organization: 'Employees State Insurance Corporation',
      category: 'Healthcare',
      sub_category: 'Central Social Security Healthcare',
      qualification: 'MBBS / Nursing',
      degree_required: 'Diploma in General Nursing and Midwifery (GNM) or B.Sc Nursing',
      age_min: 18,
      age_max: 37,
      salary_min: 44900,
      salary_max: 142400,
      pay_level: 'Level 7',
      in_hand_salary: '₹60,000 - ₹72,000 / month',
      difficulty: 'intermediate',
      frequency: 'Periodic',
      job_type: 'Medical',
      state: 'All India',
      description: 'Staff nurse, pharmacist, lab technician, and radiographer recruitment in ESIC hospitals and model dispensaries.',
      selection_process: JSON.stringify(['Computer Based Written Examination (125 Qs: Technical Professional Knowledge 100 Qs + General Aptitude 25 Qs)', 'Document Verification']),
      exam_pattern_summary: '125 Questions (125 Marks, 120 Minutes). 1/4th Negative Marking.',
      official_url: 'https://esic.gov.in',
      last_verified: '2026-08-20',
      status: 'Upcoming',
      is_popular: 1,
      is_featured: 0,
      total_marks: 125,
      duration_minutes: 120,
      dates: {
        cycle_name: 'ESIC Healthcare 2026',
        year: 2026,
        notification_date: '2026-03-10',
        application_start: '2026-03-10',
        application_end: '2026-04-05',
        admit_card_date: '2026-06-15',
        exam_date: '2026-07-07',
        result_date: '2026-08-20',
        interview_date: null,
        final_result_date: '2026-11-10',
        status: 'Upcoming'
      }
    }
  ];
}

module.exports = { getDiscoveryExams };
